/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompraExitosaRouteImport } from './routes/compra-exitosa'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicDescargarRouteImport } from './routes/api/public/descargar'

const CompraExitosaRoute = CompraExitosaRouteImport.update({
  id: '/compra-exitosa',
  path: '/compra-exitosa',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDescargarRoute = ApiPublicDescargarRouteImport.update({
  id: '/api/public/descargar',
  path: '/api/public/descargar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/compra-exitosa': typeof CompraExitosaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/descargar': typeof ApiPublicDescargarRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/compra-exitosa': typeof CompraExitosaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/descargar': typeof ApiPublicDescargarRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/compra-exitosa': typeof CompraExitosaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/descargar': typeof ApiPublicDescargarRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/compra-exitosa'
    | '/admin'
    | '/api/chat'
    | '/api/public/descargar'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/compra-exitosa'
    | '/admin'
    | '/api/chat'
    | '/api/public/descargar'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/biblioteca'
    | '/compra-exitosa'
    | '/_authenticated/admin'
    | '/api/chat'
    | '/api/public/descargar'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CompraExitosaRoute: typeof CompraExitosaRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicDescargarRoute: typeof ApiPublicDescargarRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compra-exitosa': {
      id: '/compra-exitosa'
      path: '/compra-exitosa'
      fullPath: '/compra-exitosa'
      preLoaderRoute: typeof CompraExitosaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/descargar': {
      id: '/api/public/descargar'
      path: '/api/public/descargar'
      fullPath: '/api/public/descargar'
      preLoaderRoute: typeof ApiPublicDescargarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  CompraExitosaRoute: CompraExitosaRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicDescargarRoute: ApiPublicDescargarRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
